/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lesson5 from "./lesson5";
export type { lesson5 };
import type * as lesson6 from "./lesson6";
export type { lesson6 };
import type * as lesson7 from "./lesson7";
export type { lesson7 };
