/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fundsSol from "./Funds.sol";
export type { fundsSol };
export type { Donation } from "./Donation";
export type { FailingReceiver } from "./FailingReceiver";
