/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FoundationContract__factory } from "./FoundationContract__factory";
export { Funds__factory } from "./Funds__factory";
