/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { Donation } from "./contracts/Donation";
export { Donation__factory } from "./factories/contracts/Donation__factory";
export type { FailingReceiver } from "./contracts/FailingReceiver";
export { FailingReceiver__factory } from "./factories/contracts/FailingReceiver__factory";
export type { FoundationContract } from "./contracts/Funds.sol/FoundationContract";
export { FoundationContract__factory } from "./factories/contracts/Funds.sol/FoundationContract__factory";
export type { Funds } from "./contracts/Funds.sol/Funds";
export { Funds__factory } from "./factories/contracts/Funds.sol/Funds__factory";
