/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Donation } from "./Donation";
export type { FailingReceiver } from "./FailingReceiver";
export * as factories from "./factories";
export { Donation__factory } from "./factories/Donation__factory";
export { FailingReceiver__factory } from "./factories/FailingReceiver__factory";
