/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ercSol from "./Erc.sol";
export * as fundsSol from "./Funds.sol";
export { Donation__factory } from "./Donation__factory";
export { FailingReceiver__factory } from "./FailingReceiver__factory";
