/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface UniswapV3AdapterInterface extends utils.Interface {
  functions: {
    "collectAllFees(uint256)": FunctionFragment;
    "createPool(address,address,uint24,uint160)": FunctionFragment;
    "decreaseLiquidity(uint256,uint128)": FunctionFragment;
    "encodePriceSqrt(uint256,uint256)": FunctionFragment;
    "increaseLiquidity(uint256,uint256,uint256)": FunctionFragment;
    "mintNewPosition(address,address,uint24,uint256,uint256,int24,int24)": FunctionFragment;
    "nonfungiblePositionManager()": FunctionFragment;
    "positions(uint256)": FunctionFragment;
    "sortTokens(address,address)": FunctionFragment;
    "swapExactInput(address,uint256,uint256,bytes)": FunctionFragment;
    "swapExactOutput(address,uint256,uint256,bytes)": FunctionFragment;
    "swapRouter()": FunctionFragment;
    "testSqrt(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "collectAllFees"
      | "createPool"
      | "decreaseLiquidity"
      | "encodePriceSqrt"
      | "increaseLiquidity"
      | "mintNewPosition"
      | "nonfungiblePositionManager"
      | "positions"
      | "sortTokens"
      | "swapExactInput"
      | "swapExactOutput"
      | "swapRouter"
      | "testSqrt"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "collectAllFees",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseLiquidity",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "encodePriceSqrt",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseLiquidity",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintNewPosition",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nonfungiblePositionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "sortTokens",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactInput",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactOutput",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSqrt",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "collectAllFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodePriceSqrt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintNewPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nonfungiblePositionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sortTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapExactInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "testSqrt", data: BytesLike): Result;

  events: {
    "FeesCollected(uint256,address,uint256,uint256)": EventFragment;
    "LiquidityDecreased(uint256,address,uint256,uint256,uint128)": EventFragment;
    "LiquidityIncreased(uint256,address,uint128,uint256,uint256)": EventFragment;
    "NewPositionMinted(uint256,address,address,address,uint128,uint256,uint256)": EventFragment;
    "PoolCreated(address,address,address,uint24,uint160)": EventFragment;
    "SwapExactOutputExecuted(address,uint256,uint256,bytes)": EventFragment;
    "SwapExecuted(address,uint256,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FeesCollected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiquidityDecreased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiquidityIncreased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewPositionMinted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PoolCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapExactOutputExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapExecuted"): EventFragment;
}

export interface FeesCollectedEventObject {
  tokenId: BigNumber;
  owner: string;
  amount0: BigNumber;
  amount1: BigNumber;
}
export type FeesCollectedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  FeesCollectedEventObject
>;

export type FeesCollectedEventFilter = TypedEventFilter<FeesCollectedEvent>;

export interface LiquidityDecreasedEventObject {
  tokenId: BigNumber;
  owner: string;
  amount0: BigNumber;
  amount1: BigNumber;
  liquidity: BigNumber;
}
export type LiquidityDecreasedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, BigNumber],
  LiquidityDecreasedEventObject
>;

export type LiquidityDecreasedEventFilter =
  TypedEventFilter<LiquidityDecreasedEvent>;

export interface LiquidityIncreasedEventObject {
  tokenId: BigNumber;
  owner: string;
  liquidity: BigNumber;
  amount0: BigNumber;
  amount1: BigNumber;
}
export type LiquidityIncreasedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, BigNumber],
  LiquidityIncreasedEventObject
>;

export type LiquidityIncreasedEventFilter =
  TypedEventFilter<LiquidityIncreasedEvent>;

export interface NewPositionMintedEventObject {
  tokenId: BigNumber;
  owner: string;
  token0: string;
  token1: string;
  liquidity: BigNumber;
  amount0: BigNumber;
  amount1: BigNumber;
}
export type NewPositionMintedEvent = TypedEvent<
  [BigNumber, string, string, string, BigNumber, BigNumber, BigNumber],
  NewPositionMintedEventObject
>;

export type NewPositionMintedEventFilter =
  TypedEventFilter<NewPositionMintedEvent>;

export interface PoolCreatedEventObject {
  pair: string;
  token0: string;
  token1: string;
  fee: number;
  sqrtPriceX96: BigNumber;
}
export type PoolCreatedEvent = TypedEvent<
  [string, string, string, number, BigNumber],
  PoolCreatedEventObject
>;

export type PoolCreatedEventFilter = TypedEventFilter<PoolCreatedEvent>;

export interface SwapExactOutputExecutedEventObject {
  tokenIn: string;
  amountOut: BigNumber;
  amountIn: BigNumber;
  path: string;
}
export type SwapExactOutputExecutedEvent = TypedEvent<
  [string, BigNumber, BigNumber, string],
  SwapExactOutputExecutedEventObject
>;

export type SwapExactOutputExecutedEventFilter =
  TypedEventFilter<SwapExactOutputExecutedEvent>;

export interface SwapExecutedEventObject {
  tokenIn: string;
  amountIn: BigNumber;
  amountOut: BigNumber;
  path: string;
}
export type SwapExecutedEvent = TypedEvent<
  [string, BigNumber, BigNumber, string],
  SwapExecutedEventObject
>;

export type SwapExecutedEventFilter = TypedEventFilter<SwapExecutedEvent>;

export interface UniswapV3Adapter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UniswapV3AdapterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    collectAllFees(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createPool(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      sqrtPriceX96: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    decreaseLiquidity(
      tokenId: PromiseOrValue<BigNumberish>,
      liquidity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    encodePriceSqrt(
      reserve0: PromiseOrValue<BigNumberish>,
      reserve1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { sqrtPriceX96: BigNumber }>;

    increaseLiquidity(
      tokenId: PromiseOrValue<BigNumberish>,
      amountAdd0: PromiseOrValue<BigNumberish>,
      amountAdd1: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    mintNewPosition(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      poolFee: PromiseOrValue<BigNumberish>,
      amount0ToMint: PromiseOrValue<BigNumberish>,
      amount1ToMint: PromiseOrValue<BigNumberish>,
      minTick: PromiseOrValue<BigNumberish>,
      maxTick: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<[string]>;

    positions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber] & {
        owner: string;
        token0: string;
        token1: string;
        liquidity: BigNumber;
      }
    >;

    sortTokens(
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { token0: string; token1: string }>;

    swapExactInput(
      tokenIn: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      amountOutMinimum: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapExactOutput(
      tokenIn: PromiseOrValue<string>,
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<[string]>;

    testSqrt(
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  collectAllFees(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createPool(
    token0: PromiseOrValue<string>,
    token1: PromiseOrValue<string>,
    fee: PromiseOrValue<BigNumberish>,
    sqrtPriceX96: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  decreaseLiquidity(
    tokenId: PromiseOrValue<BigNumberish>,
    liquidity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  encodePriceSqrt(
    reserve0: PromiseOrValue<BigNumberish>,
    reserve1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  increaseLiquidity(
    tokenId: PromiseOrValue<BigNumberish>,
    amountAdd0: PromiseOrValue<BigNumberish>,
    amountAdd1: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  mintNewPosition(
    token0: PromiseOrValue<string>,
    token1: PromiseOrValue<string>,
    poolFee: PromiseOrValue<BigNumberish>,
    amount0ToMint: PromiseOrValue<BigNumberish>,
    amount1ToMint: PromiseOrValue<BigNumberish>,
    minTick: PromiseOrValue<BigNumberish>,
    maxTick: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  nonfungiblePositionManager(overrides?: CallOverrides): Promise<string>;

  positions(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber] & {
      owner: string;
      token0: string;
      token1: string;
      liquidity: BigNumber;
    }
  >;

  sortTokens(
    tokenA: PromiseOrValue<string>,
    tokenB: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[string, string] & { token0: string; token1: string }>;

  swapExactInput(
    tokenIn: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    amountOutMinimum: PromiseOrValue<BigNumberish>,
    path: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapExactOutput(
    tokenIn: PromiseOrValue<string>,
    amountOut: PromiseOrValue<BigNumberish>,
    amountInMaximum: PromiseOrValue<BigNumberish>,
    path: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapRouter(overrides?: CallOverrides): Promise<string>;

  testSqrt(
    y: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    collectAllFees(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amount0: BigNumber; amount1: BigNumber }
    >;

    createPool(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      sqrtPriceX96: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    decreaseLiquidity(
      tokenId: PromiseOrValue<BigNumberish>,
      liquidity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amount0: BigNumber; amount1: BigNumber }
    >;

    encodePriceSqrt(
      reserve0: PromiseOrValue<BigNumberish>,
      reserve1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    increaseLiquidity(
      tokenId: PromiseOrValue<BigNumberish>,
      amountAdd0: PromiseOrValue<BigNumberish>,
      amountAdd1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        liquidity: BigNumber;
        amount0: BigNumber;
        amount1: BigNumber;
      }
    >;

    mintNewPosition(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      poolFee: PromiseOrValue<BigNumberish>,
      amount0ToMint: PromiseOrValue<BigNumberish>,
      amount1ToMint: PromiseOrValue<BigNumberish>,
      minTick: PromiseOrValue<BigNumberish>,
      maxTick: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        tokenId: BigNumber;
        liquidity: BigNumber;
        amount0: BigNumber;
        amount1: BigNumber;
      }
    >;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<string>;

    positions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber] & {
        owner: string;
        token0: string;
        token1: string;
        liquidity: BigNumber;
      }
    >;

    sortTokens(
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { token0: string; token1: string }>;

    swapExactInput(
      tokenIn: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      amountOutMinimum: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExactOutput(
      tokenIn: PromiseOrValue<string>,
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapRouter(overrides?: CallOverrides): Promise<string>;

    testSqrt(
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "FeesCollected(uint256,address,uint256,uint256)"(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      amount0?: null,
      amount1?: null
    ): FeesCollectedEventFilter;
    FeesCollected(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      amount0?: null,
      amount1?: null
    ): FeesCollectedEventFilter;

    "LiquidityDecreased(uint256,address,uint256,uint256,uint128)"(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      amount0?: null,
      amount1?: null,
      liquidity?: null
    ): LiquidityDecreasedEventFilter;
    LiquidityDecreased(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      amount0?: null,
      amount1?: null,
      liquidity?: null
    ): LiquidityDecreasedEventFilter;

    "LiquidityIncreased(uint256,address,uint128,uint256,uint256)"(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      liquidity?: null,
      amount0?: null,
      amount1?: null
    ): LiquidityIncreasedEventFilter;
    LiquidityIncreased(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      liquidity?: null,
      amount0?: null,
      amount1?: null
    ): LiquidityIncreasedEventFilter;

    "NewPositionMinted(uint256,address,address,address,uint128,uint256,uint256)"(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      token0?: null,
      token1?: null,
      liquidity?: null,
      amount0?: null,
      amount1?: null
    ): NewPositionMintedEventFilter;
    NewPositionMinted(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      token0?: null,
      token1?: null,
      liquidity?: null,
      amount0?: null,
      amount1?: null
    ): NewPositionMintedEventFilter;

    "PoolCreated(address,address,address,uint24,uint160)"(
      pair?: PromiseOrValue<string> | null,
      token0?: PromiseOrValue<string> | null,
      token1?: PromiseOrValue<string> | null,
      fee?: null,
      sqrtPriceX96?: null
    ): PoolCreatedEventFilter;
    PoolCreated(
      pair?: PromiseOrValue<string> | null,
      token0?: PromiseOrValue<string> | null,
      token1?: PromiseOrValue<string> | null,
      fee?: null,
      sqrtPriceX96?: null
    ): PoolCreatedEventFilter;

    "SwapExactOutputExecuted(address,uint256,uint256,bytes)"(
      tokenIn?: PromiseOrValue<string> | null,
      amountOut?: null,
      amountIn?: null,
      path?: null
    ): SwapExactOutputExecutedEventFilter;
    SwapExactOutputExecuted(
      tokenIn?: PromiseOrValue<string> | null,
      amountOut?: null,
      amountIn?: null,
      path?: null
    ): SwapExactOutputExecutedEventFilter;

    "SwapExecuted(address,uint256,uint256,bytes)"(
      tokenIn?: PromiseOrValue<string> | null,
      amountIn?: null,
      amountOut?: null,
      path?: null
    ): SwapExecutedEventFilter;
    SwapExecuted(
      tokenIn?: PromiseOrValue<string> | null,
      amountIn?: null,
      amountOut?: null,
      path?: null
    ): SwapExecutedEventFilter;
  };

  estimateGas: {
    collectAllFees(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createPool(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      sqrtPriceX96: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    decreaseLiquidity(
      tokenId: PromiseOrValue<BigNumberish>,
      liquidity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    encodePriceSqrt(
      reserve0: PromiseOrValue<BigNumberish>,
      reserve1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    increaseLiquidity(
      tokenId: PromiseOrValue<BigNumberish>,
      amountAdd0: PromiseOrValue<BigNumberish>,
      amountAdd1: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    mintNewPosition(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      poolFee: PromiseOrValue<BigNumberish>,
      amount0ToMint: PromiseOrValue<BigNumberish>,
      amount1ToMint: PromiseOrValue<BigNumberish>,
      minTick: PromiseOrValue<BigNumberish>,
      maxTick: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<BigNumber>;

    positions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sortTokens(
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExactInput(
      tokenIn: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      amountOutMinimum: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapExactOutput(
      tokenIn: PromiseOrValue<string>,
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapRouter(overrides?: CallOverrides): Promise<BigNumber>;

    testSqrt(
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    collectAllFees(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createPool(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      sqrtPriceX96: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    decreaseLiquidity(
      tokenId: PromiseOrValue<BigNumberish>,
      liquidity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    encodePriceSqrt(
      reserve0: PromiseOrValue<BigNumberish>,
      reserve1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    increaseLiquidity(
      tokenId: PromiseOrValue<BigNumberish>,
      amountAdd0: PromiseOrValue<BigNumberish>,
      amountAdd1: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    mintNewPosition(
      token0: PromiseOrValue<string>,
      token1: PromiseOrValue<string>,
      poolFee: PromiseOrValue<BigNumberish>,
      amount0ToMint: PromiseOrValue<BigNumberish>,
      amount1ToMint: PromiseOrValue<BigNumberish>,
      minTick: PromiseOrValue<BigNumberish>,
      maxTick: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    nonfungiblePositionManager(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    positions(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sortTokens(
      tokenA: PromiseOrValue<string>,
      tokenB: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapExactInput(
      tokenIn: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      amountOutMinimum: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapExactOutput(
      tokenIn: PromiseOrValue<string>,
      amountOut: PromiseOrValue<BigNumberish>,
      amountInMaximum: PromiseOrValue<BigNumberish>,
      path: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testSqrt(
      y: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
